os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=0
    - CONAN_REFERENCE="benchmark/1.4.0"
    - CONAN_USERNAME="jjones646"
    - CONAN_CHANNEL="testing"
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=6.4 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.4 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.4 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.4 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=7.1 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=7.1 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=7.1 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=7.1 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4 CONAN_USE_DOCKER=1

matrix:
  include:
    - os: osx
      osx_image: xcode8   # apple-clang 8.0
      language: generic
      env:
      - os: osx
      osx_image: xcode8.1 # apple-clang 8.1
      language: generic
      env:
    - os: osx
      osx_image: xcode9   # apple-clang 9.0
      language: generic
      env:

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
